allowBuilds:
  '@prisma/engines': false
  esbuild: true
  prisma: true
  sharp: true
minimumReleaseAgeExclude:
  - '@astrojs/node@10.1.3'
  - astro@6.4.3
onlyBuiltDependencies:
  - '@prisma/engines'
  - esbuild
  - prisma
  - sharp
